// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj6qyvCTlJeCUMpgHTPrbNjkjDfoHJePM',
    appId: '1:990860438806:web:841ad9a59712a05f163437',
    messagingSenderId: '990860438806',
    projectId: 'fir-flutter-codelab-42680',
    authDomain: 'fir-flutter-codelab-42680.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-42680.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xtdCR2k8wxjKC3LnPMyhnIIwyoFvmG4',
    appId: '1:990860438806:android:c3ccd68489c0dfc3163437',
    messagingSenderId: '990860438806',
    projectId: 'fir-flutter-codelab-42680',
    storageBucket: 'fir-flutter-codelab-42680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkx1ZxTTOqNb5P6OxKODMd6YaWRoFMvqc',
    appId: '1:990860438806:ios:dc8bc069a4e7cccf163437',
    messagingSenderId: '990860438806',
    projectId: 'fir-flutter-codelab-42680',
    storageBucket: 'fir-flutter-codelab-42680.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkx1ZxTTOqNb5P6OxKODMd6YaWRoFMvqc',
    appId: '1:990860438806:ios:dc8bc069a4e7cccf163437',
    messagingSenderId: '990860438806',
    projectId: 'fir-flutter-codelab-42680',
    storageBucket: 'fir-flutter-codelab-42680.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
